# Numpy

Importing Numpy with alias name and creating a first matrix of zeros using `np.zeros()` method of order (10 X 10)

In [13]:
import numpy as np #alias

matrix=np.zeros((10,10)) #Order 10 X 10

In [14]:
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
b = np.array([[1,23,4,5],[4,5,6,8]])
print(b)

[[ 1 23  4  5]
 [ 4  5  6  8]]


In [17]:
print(b.ndim)
print(matrix.shape) #This is for printing shape

2
2
(10, 10)


In [20]:
b = np.array([[1,23,4,5],[4,5,6,8]] , dtype = 'int8')


In [21]:
# Get type
matrix.dtype

dtype('float64')

In [22]:
b.dtype

dtype('int8')

In [23]:
b.itemsize

1

In [24]:
matrix.itemsize

8

In [25]:
b.itemsize

1

In [28]:
list1 = [[1 ,3, 4],
[5, 6, 8 ],
[3, 5, 7]]

list2 = [[3 ,3, 4],
[5, 6, 9 ],
[3, 9, 5 ]]

print(list1*list2)

TypeError: can't multiply sequence by non-int of type 'list'

In [29]:
value1 = np.array([[1 ,3, 4],
                            [5, 6, 8 ],
                            [3, 5, 7]])

value2 = np.array([[3 ,3, 4],
                            [5, 6, 9 ],
                            [3, 9, 5 ]])

print(value1*value2)


print(value1@value2)

[[ 3  9 16]
 [25 36 72]
 [ 9 45 35]]
[[ 30  57  51]
 [ 69 123 114]
 [ 55 102  92]]


In [31]:
a = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

indices = np.array([[True, False, True],
                            [True, False, True],
                            [True, False, False]])

print(a[indices])

[1 3 4 6 7]
